# Generated by Django 4.2.4 on 2023-12-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fechaInscripcion', models.DateField()),
                ('hora_inscripcion', models.TimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO ASISTEN', 'No Asisten')], max_length=20)),
                ('observacion', models.CharField(max_length=500)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminario_app.instituciones')),
            ],
        ),
    ]
