# Generated by Django 4.2.6 on 2023-12-22 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seminario_app.instituciones'),
        ),
    ]
