# Generated by Django 4.2.6 on 2023-12-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_app', '0003_rename_hora_inscripcion_inscritos_horainscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='fechaInscripcion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
